stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    
variables:
  CI: ""

build:
  stage: build
  image: node:11
  script:
    - npm install --progress=false
    - npm run build

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=cristianpoptema1frontend --api-key=$HEROKU_API_KEY --skip_cleanup
  #environment:
    #name: staging
    #url: https://cristianpoptema1frontend.herokuapp.com/
  only:
    - master
